#!/usr/bin/python3
import sys

def factorize(n):
    if n % 2 == 0:
        return n // 2, 2
    i = 3
    while i * i <= n:
        if n % i == 0:
            return n // i, i
        i += 2
    return n, 1

if __name__ == "__main__":
    with open(sys.argv[1]) as f:
        for line in f:
            n = int(line)
            p, q = factorize(n)
            print(f"{n}={p}*{q}")
